version: '3.8'

services:
  cosmos-hgp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/log
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
